### ISSUE TITLE
Enterprise Console API endpoints are not documented

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#313] opened 2018-03-30 21:27 UTC
The Sensu Enterprise Console API provides a federated front-end to multiple Sensu API instances. This makes it possible to query multiple datacenters with a single API call. Unfortunately the Console API does not implement 1:1 support for each endpoint offered by the Sensu API, and we haven't documented these differences.

Here's a list of what is known to be supported:

```
/aggregates (GET)
/aggregates/:aggregate (GET, DELETE)
/checks (GET)
/checks/:check (GET, DELETE)
/checks/:check (GET, DELETE)
/clients (GET)
/clients/:client (GET, DELETE)
/clients/:client/history (GET)
/config (GET)
/datacenters (GET)
/datacenters/ (GET)
/events (GET)
/events/:client/:check (DELETE)
/request (POST)
/results/:client/:check (DELETE)
/silenced (GET, POST)
/silenced/:id (GET)
/silenced/clear (POST)
/stashes/:path (DELETE)
/stashes (GET, POST)
/subscriptions (GET)
/subscriptions/:subscription (GET)
```

Note: POST operations require `dc` attribute to specify the target datacenter.

**Comment by apaskulin** [comment] 2018-09-24 20:50
Closing as a duplicate of #561

**Closed as completed** 2018-09-24 20:51 UTC
Labels: new doc
