### ISSUE TITLE
Weird info in banner when viewing older versions

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#435] opened 2018-05-24 17:47 UTC
## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior
I would expect to see the variable show the value it's supposed to be representing.

## Current Behavior
![weird-docs-info](https://user-images.githubusercontent.com/898627/40502259-478d9e4a-5f3f-11e8-9a65-19719b60488c.png)

## Steps to Reproduce (for bugs)

To be honest, I wasn't able to record all the clicks I made in the docs to get to this point, but the URL I ended up at was https://docs.sensu.io/sensu-core/1.0/guides/adding-a-client/#add-a-remote-sensu-client

**Comment by dabria** [comment] 2018-05-24 18:20
The front matter for this page needs to be updated with `product` most likely.

**Comment by apaskulin** [comment] 2018-05-31 20:40
In the screenshot, it looks like the products dropdown has "Projects" selected even though the URL is `sensu-core` 🤔 which is likely causing the weirdness. This isn't happening on the live version of the page, and I wasn't able to reproduce that dropdown state.

Any ideas how this happened, @asachs01? Or should we close for now?

**Comment by asachs01** [comment] 2018-06-15 14:55
I think we can close this out. I've not been able to replicate it.

**Comment by apaskulin** [comment] 2018-06-22 15:34
Found this! `product` frontmatter missing from https://github.com/sensu/sensu-docs/blob/master/content/sensu-core/1.0/guides/intro-to-checks.md. Assigning to myself as part of general frontmatter cleanup

**Closed as completed** 2018-06-26 15:03 UTC
Labels: bug
