### ISSUE TITLE
404 errors when navigating between product versions when a page exists in one but not the other

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#1209] opened 2019-02-15 02:14 UTC
## This is an issue with:

- [X] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
For example, when on version 5.2 of Sensu Go and you are on a page that only exists there:
https://docs.sensu.io/sensu-go/5.2/reference/license/
And change the version of the drop down to another version, say 5.1
https://docs.sensu.io/sensu-go/5.1/reference/license/

Instead of a 404 error, handle more gracefully.

## Current Behavior
Doing the above described action results in 404 error.

## Possible Solution
Send to that product's "home page" for that version.
Possible this issue is covered in another ticket regarding 404s, but could not find one easily.

## Steps to Reproduce (for bugs)

1. Go to https://docs.sensu.io/sensu-go/5.2/reference/license/
2. Switch version from 5.2 to 5.1
3. Observe 404 error.

## Context
Make users browsing of the docs site better.

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment] 2019-02-15 16:32
This is another possible solution for #869. I think I'd still prefer placeholder pages to some kind of intelligent 404 handling.

**Comment by rgeniesse** [comment] 2019-02-15 18:56
Placeholder pages make sense to me. Covers the 404 and informs the user that they need to upgrade.

If you'd like to track this page in #869 as well and close this, I am all for that.

**Comment by apaskulin** [comment] 2019-02-15 19:13
Thanks! Closing as a duplicate of #447 and #869

**Closed as completed by apaskulin** 2019-02-15 19:13 UTC
Labels: bug
