### ISSUE TITLE
Explore creating SE install docs in SE section

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#365] opened 2018-04-17 13:56 UTC
One thing that was raised yesterday by a customer is that SE install docs are a bit difficult to find if you're expecting them to be in the SE section of the site. It might lead to a better ux for us to create install docs under the SE section, rather than lumping all the install docs under Core.

**Comment by apaskulin** [comment] 2018-09-13 18:35
Closing as a duplicate of #731

**Closed as completed by apaskulin** 2018-09-13 18:35 UTC
Labels: enhancement
