### ISSUE TITLE
Create Sensu Go Getting Started Series

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#893] opened 2018-11-08 23:12 UTC
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

Series of articles aimed at beginners getting their feet wet w/ Sensu Go. This could be adapted from sensu/sandbox

**Comment by apaskulin** [comment] 2018-11-09 16:34
Closing as a duplicate of #842

**Closed as completed by apaskulin** 2018-11-09 16:34 UTC
