### ISSUE TITLE
Sensu core version 1.4 shows Quick Start under Quick Start sidebar option

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#606] opened 2018-07-25 19:40 UTC
## This is an issue with:

- [X] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Not sure if this is a bug with 1.4 or a missing piece for the other versions

## Current Behavior
Seen screen shot.

## Possible Solution
Decide which way to fix it, either remove from 1.4 or add to other versions.

## Screenshots (if appropriate):

<img width="731" alt="screen shot 2018-07-25 at 12 30 49 pm" src="https://user-images.githubusercontent.com/19964713/43223418-e265a022-9007-11e8-998e-1b0f60c528a6.png">

**Comment by apaskulin** [comment] 2018-07-27 16:15
Do you mind if we close this as a duplicate of #581?

**Comment by asachs01** [comment] 2018-07-30 16:55
Doing ^

**Closed as completed by asachs01** 2018-07-30 16:55 UTC
Labels: bug, duplicate
