### ISSUE TITLE
JSON Invalid

### ISSUE THREAD

**Issue by SiqingYu** [sensu/sensu-docs#1311] opened 2019-03-15 12:09 UTC
https://docs.sensu.io/sensu-go/5.3/guides/monitor-external-resources/#creating-proxy-entities

`entities.json` isn't a valid JSON file, as show by https://jsonlint.com/
However it works with Sensu Go.

```json
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "name": "sensu-docs",
    "namespace": "default",
    "labels": {
      "proxy_type": "website",
      "url": "https://docs.sensu.io"
    }
  },
  "spec": {
    "entity_class": "proxy"
  }
}
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "name": "packagecloud-site",
    "namespace": "default",
    "labels": {
      "proxy_type": "website",
      "url": "https://packagecloud.io"
    }
  },
  "spec": {
    "entity_class": "proxy"
  }
}
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "name": "github-site",
    "namespace": "default",
    "labels": {
      "proxy_type": "website",
      "url": "https://github.com"
    }
  },
  "spec": {
    "entity_class": "proxy"
  }
}
```

**Comment by asachs01** [comment] 2019-03-15 13:54
Hi @SiqingYu . This is as intended. Each stanza should be evaluated on its own for validity, not the document as a whole. That is, each instance of:
```
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "name": "github-site",
    "namespace": "default",
    "labels": {
      "proxy_type": "website",
      "url": "https://github.com"
    }
  },
  "spec": {
    "entity_class": "proxy"
  }
```
Should show as valid. It's perhaps easier to see something like this in yaml, and I believe we're going to be providing that option in the future. 

That said, I can understand the confusion that arises when viewing this via an editor or jsonlint. If this is something you feel we need to call out in the documentation, let us know. As it stands, I'll close this and note that the json in the docs is exactly as it should be for this example.

**Closed as completed by asachs01** 2019-03-15 13:54 UTC
Labels: wontfix
