### ISSUE TITLE
New URL for sandbox dashboard?

### ISSUE THREAD

**Issue by bananabele** [sensu/sensu-docs#1755] opened 2019-09-13 15:26 UTC
Link to page: https://docs.sensu.io/sensu-go/5.13/getting-started/learn-sensu/

### Feedback
The sandbox dashboard (linked in the above lesson plan as well as the Learn Sensu Go course) uses this link: http://localhost:3002/signin
which gives the following error:
<img width="505" alt="Screen Shot 2019-09-13 at 10 05 42 AM" src="https://user-images.githubusercontent.com/38439765/64874553-db628b00-d610-11e9-8f8b-d02ac5c13ece.png">
making it https doesn't fix the issue (it just 404s). Is there a new link we should use?

**Comment by asachs01** [comment] 2019-09-16 20:34
@cwjohnston @bananabele and I spent some time on this today. The issue is w/ local storage needing to be cleared. Once we did that, things were 👌 . The challenge is, I think, is to have better error handling and perhaps some instructive troubleshooting for users around localstorage. Though I'm not immediately clear about the instructions unless we have a more useful error.

**Comment by asachs01** [comment] 2019-09-18 13:59
@bananabele I'm going to close this for now and defer to https://github.com/sensu/web/issues/199 with the web team.

**Closed as completed by asachs01** 2019-09-18 13:59 UTC
