### ISSUE TITLE
Check reference docs should not describe auto-remediation in `hooks` examples

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#442] opened 2018-05-29 22:41 UTC
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior

Check reference documentation for `hooks` feature should describe recommended use cases.

## Current Behavior

Check reference documentation for `hooks` feature illustrates an example of "auto-remediation" which is a "worst-practice" for this feature.

## Possible Solution

Replace the auto-remediation example with something more in-line with our recommended practices.

## Context

(Re)starting nginx repeatedly might not actually remediate the problem 😉

**Comment by apaskulin** [comment] 2018-05-30 00:05
Oops! Looks like this is a duplicate of #367

**Closed as completed by apaskulin** 2018-05-30 00:05 UTC
Labels: errata
