### ISSUE TITLE
Check hook documentation is incorrect for 2.x

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#401] opened 2018-05-07 05:00 UTC
Sensu check hooks must be specified in the following way:

```
{
    "check_hooks": {
        "non-zero": ["hook_1"]
    }
}
```

However, the documentation states that check hooks are to be specified as an array.

Fix the incorrect documentation, and provide a correct example.

**Comment by apaskulin** [comment] 2018-09-24 20:59
Closing as a duplicate of #678

**Closed as completed by apaskulin** 2018-09-24 20:59 UTC
Labels: errata
